---

- name: Upload docker jenkins
  copy:
    src: "{{ playbook_dir }}/docker-compose.yml"
    dest: "docker-compose.yml"

- name: Create docker service and run
  community.docker.docker_compose:
    project_src: .
  register: output

- name: Print docker-compose output
  debug:
    var: output