---
- name: Upload docker jenkins
  copy:
    src: "{{ playbook_dir }}/docker-compose.yml"
    dest: "docker-compose.yml"

- name: Create docker service and run
  community.docker.docker_compose:
    project_src: .
  register: output

- name: Capture initial password
  docker_volume_info:
    name: "{{ ansible_user }}_jenkins-volume"
  register: result

- name: Store init password jenkins
  shell: cat "{{ result.volume.Mountpoint }}/secrets/initialAdminPassword"
  register: initPassword

- name: Debug initial admin password
  debug:
    msg: "initial admin password is {{ initPassword.stdout }}"
